---
name: aliased
version: 0.20
author:
  - Curtis "Ovid" Poe <moc.oohay@eop_divo_sitruc>
abstract: Use shorter versions of class names.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0.6
provides:
  aliased:
    file: lib/aliased.pm
    version: 0.20
generated_by: Module::Build version 0.2702
